# Generated by Django 5.2.1 on 2025-05-18 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 5, 18, 7, 10, 2, 789313, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
