# Generated by Django 5.2.1 on 2025-06-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_delete_library'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
