# Generated by Django 5.2.1 on 2025-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
