# Generated by Django 5.2.1 on 2025-05-18 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 18, 7, 14, 28, 956623, tzinfo=datetime.timezone.utc)),
        ),
    ]
