# Generated by Django 5.2.1 on 2025-05-18 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_promptlog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
