# Generated by Django 5.2.1 on 2025-05-19 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('recommendations', '0003_alter_promptlog_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('prompt_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.promptlog')),
            ],
        ),
    ]
