# Generated by Django 5.2.1 on 2025-05-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_library_rename_isbn_book_isbn13'),
        ('recommendations', '0004_recommendedbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedbook',
            name='prompt_log',
        ),
        migrations.RemoveField(
            model_name='recommendedbook',
            name='book',
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
        migrations.DeleteModel(
            name='PromptLog',
        ),
        migrations.DeleteModel(
            name='RecommendedBook',
        ),
    ]
