# Generated by Django 5.2.1 on 2025-05-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lib_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='isbn13',
        ),
    ]
