# Generated by Django 5.2.1 on 2025-06-23 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_library_rename_isbn_book_isbn13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
